project:
  type: website

website:
  title: "Introduction to Bioinformatics"
  site-url: https://brianrepko.github.io/intro-to-bioinfo
  description: "A five-part overview"

format:
  html:
    theme:
      - sandstone
      - brand