---
title: "Introduction to Bioinformatics"
subtitle: "Regulation, RNAi, and Epigenetics"
format: revealjs
---

# Overview and Agenda {visibility="hidden"}

## [Series](../){target="_blank"} Overview

- Five 1 hour sessions
  - Very high level - just meant to organize concepts
- Part 1 - Biology "down to the cell"
- Part 2 - -omics, Molecular / Structural biology
  - 2a - Genomics / DNA and Transcriptomics / RNA
  - 2b - Proteomics, Metabolomics, and Variants
  - <span style="color: red;">2c - Regulation, RNAi, and Epigenetics</span>
- Part 3 - Biomedical Research

## Agenda {.smaller}

* Regulation / RNAi
  * Enhancers, Silencers, and Transcription Factors
  * RNAi - miRNA and siRNA
  * Knockdowns and Knockouts - shRNA and CRISPR
* Epigenetics
  * DNA methylation
  * Histone modification
* Metagenomics
* Phylogenomics

# Regulation / RNAi

## Terms

## Regulation of Transcription

## RNA Interference (RNAi)

## miRNA and siRNA

## Knockdowns and Knockouts

# Epigenetics {visibility="hidden"}

## Epigenetics

## DNA methylation

## Histone Modifications

## Histone Code

## Heritability

## Databases / Resources

# Extra topics {visibility="hidden"}

## Metagenomics

## Phylogenomics

# Next Session {visibility="hidden"}

## [Next Session](../session3/){target="_blank"} Preview {.smaller}

* Drug Discovery Process
* Disease and Epidemiology
* Target ID and Validation
* In-vitro and In-vivo Studies
* Therpeutics Development
* Translational and Clinical Studies

